// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: child.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V []string `protobuf:"bytes,1,rep,name=V,proto3" json:"V,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetV() []string {
	if x != nil {
		return x.V
	}
	return nil
}

type DoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId   int32             `protobuf:"varint,1,opt,name=AdminId,proto3" json:"AdminId,omitempty"`
	AdminName string            `protobuf:"bytes,2,opt,name=AdminName,proto3" json:"AdminName,omitempty"`
	AdminType int32             `protobuf:"varint,3,opt,name=AdminType,proto3" json:"AdminType,omitempty"`
	Uri       string            `protobuf:"bytes,5,opt,name=Uri,proto3" json:"Uri,omitempty"` //用于区分处理方法
	AdminJson string            `protobuf:"bytes,6,opt,name=AdminJson,proto3" json:"AdminJson,omitempty"`
	Header    map[string]*Value `protobuf:"bytes,7,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Query     map[string]*Value `protobuf:"bytes,8,rep,name=Query,proto3" json:"Query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PostForm  map[string]*Value `protobuf:"bytes,9,rep,name=PostForm,proto3" json:"PostForm,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body      string            `protobuf:"bytes,10,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *DoReq) Reset() {
	*x = DoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoReq) ProtoMessage() {}

func (x *DoReq) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoReq.ProtoReflect.Descriptor instead.
func (*DoReq) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{1}
}

func (x *DoReq) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *DoReq) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *DoReq) GetAdminType() int32 {
	if x != nil {
		return x.AdminType
	}
	return 0
}

func (x *DoReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DoReq) GetAdminJson() string {
	if x != nil {
		return x.AdminJson
	}
	return ""
}

func (x *DoReq) GetHeader() map[string]*Value {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DoReq) GetQuery() map[string]*Value {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *DoReq) GetPostForm() map[string]*Value {
	if x != nil {
		return x.PostForm
	}
	return nil
}

func (x *DoReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DoRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg         string            `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Body        string            `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	Header      map[string]string `protobuf:"bytes,4,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType string            `protobuf:"bytes,5,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
}

func (x *DoRep) Reset() {
	*x = DoRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRep) ProtoMessage() {}

func (x *DoRep) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRep.ProtoReflect.Descriptor instead.
func (*DoRep) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{2}
}

func (x *DoRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DoRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DoRep) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DoRep) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DoRep) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ReloadItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *ReloadItemReq) Reset() {
	*x = ReloadItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadItemReq) ProtoMessage() {}

func (x *ReloadItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadItemReq.ProtoReflect.Descriptor instead.
func (*ReloadItemReq) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{3}
}

func (x *ReloadItemReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ReloadChannelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *ReloadChannelReq) Reset() {
	*x = ReloadChannelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadChannelReq) ProtoMessage() {}

func (x *ReloadChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadChannelReq.ProtoReflect.Descriptor instead.
func (*ReloadChannelReq) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadChannelReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ReloadZoneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *ReloadZoneReq) Reset() {
	*x = ReloadZoneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadZoneReq) ProtoMessage() {}

func (x *ReloadZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadZoneReq.ProtoReflect.Descriptor instead.
func (*ReloadZoneReq) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadZoneReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ReloadRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ReloadRep) Reset() {
	*x = ReloadRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_child_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRep) ProtoMessage() {}

func (x *ReloadRep) ProtoReflect() protoreflect.Message {
	mi := &file_child_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRep.ProtoReflect.Descriptor instead.
func (*ReloadRep) Descriptor() ([]byte, []int) {
	return file_child_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReloadRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_child_proto protoreflect.FileDescriptor

var file_child_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x56, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01, 0x56,
	0x22, 0xf2, 0x03, 0x0a, 0x05, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x72, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4a, 0x73, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x05,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x6f,
	0x52, 0x65, 0x71, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72,
	0x6d, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x50,
	0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x41, 0x0a, 0x0b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x40,
	0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x43, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xca, 0x01, 0x0a, 0x05, 0x44, 0x6f, 0x52, 0x65, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x44, 0x6f, 0x52, 0x65,
	0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x52,
	0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x6f, 0x61,
	0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x22, 0x31, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x32, 0x79, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x02,
	0x44, 0x6f, 0x12, 0x06, 0x2e, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x44, 0x6f, 0x52,
	0x65, 0x70, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x11, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x12, 0x0c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x0b, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_child_proto_rawDescOnce sync.Once
	file_child_proto_rawDescData = file_child_proto_rawDesc
)

func file_child_proto_rawDescGZIP() []byte {
	file_child_proto_rawDescOnce.Do(func() {
		file_child_proto_rawDescData = protoimpl.X.CompressGZIP(file_child_proto_rawDescData)
	})
	return file_child_proto_rawDescData
}

var file_child_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_child_proto_goTypes = []interface{}{
	(*Value)(nil),            // 0: Value
	(*DoReq)(nil),            // 1: DoReq
	(*DoRep)(nil),            // 2: DoRep
	(*ReloadItemReq)(nil),    // 3: ReloadItemReq
	(*ReloadChannelReq)(nil), // 4: ReloadChannelReq
	(*ReloadZoneReq)(nil),    // 5: ReloadZoneReq
	(*ReloadRep)(nil),        // 6: ReloadRep
	nil,                      // 7: DoReq.HeaderEntry
	nil,                      // 8: DoReq.QueryEntry
	nil,                      // 9: DoReq.PostFormEntry
	nil,                      // 10: DoRep.HeaderEntry
	(*PublishInfo)(nil),      // 11: PublishInfo
	(*PublishRep)(nil),       // 12: PublishRep
}
var file_child_proto_depIdxs = []int32{
	7,  // 0: DoReq.Header:type_name -> DoReq.HeaderEntry
	8,  // 1: DoReq.Query:type_name -> DoReq.QueryEntry
	9,  // 2: DoReq.PostForm:type_name -> DoReq.PostFormEntry
	10, // 3: DoRep.Header:type_name -> DoRep.HeaderEntry
	0,  // 4: DoReq.HeaderEntry.value:type_name -> Value
	0,  // 5: DoReq.QueryEntry.value:type_name -> Value
	0,  // 6: DoReq.PostFormEntry.value:type_name -> Value
	1,  // 7: Child.Do:input_type -> DoReq
	4,  // 8: Child.ReloadChannel:input_type -> ReloadChannelReq
	11, // 9: Child.Publish:input_type -> PublishInfo
	2,  // 10: Child.Do:output_type -> DoRep
	6,  // 11: Child.ReloadChannel:output_type -> ReloadRep
	12, // 12: Child.Publish:output_type -> PublishRep
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_child_proto_init() }
func file_child_proto_init() {
	if File_child_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_child_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadChannelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadZoneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_child_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_child_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_child_proto_goTypes,
		DependencyIndexes: file_child_proto_depIdxs,
		MessageInfos:      file_child_proto_msgTypes,
	}.Build()
	File_child_proto = out.File
	file_child_proto_rawDesc = nil
	file_child_proto_goTypes = nil
	file_child_proto_depIdxs = nil
}
