// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gate.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId int32 `protobuf:"varint,1,opt,name=AdminId,proto3" json:"AdminId,omitempty"`
}

func (x *ClearAuthReq) Reset() {
	*x = ClearAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAuthReq) ProtoMessage() {}

func (x *ClearAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAuthReq.ProtoReflect.Descriptor instead.
func (*ClearAuthReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{0}
}

func (x *ClearAuthReq) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type ClearAuthRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *ClearAuthRep) Reset() {
	*x = ClearAuthRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAuthRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAuthRep) ProtoMessage() {}

func (x *ClearAuthRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAuthRep.ProtoReflect.Descriptor instead.
func (*ClearAuthRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{1}
}

func (x *ClearAuthRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{2}
}

func (x *PingReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PingRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRegister bool `protobuf:"varint,1,opt,name=isRegister,proto3" json:"isRegister,omitempty"`
}

func (x *PingRep) Reset() {
	*x = PingRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRep) ProtoMessage() {}

func (x *PingRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRep.ProtoReflect.Descriptor instead.
func (*PingRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{3}
}

func (x *PingRep) GetIsRegister() bool {
	if x != nil {
		return x.IsRegister
	}
	return false
}

type RegisterRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *RegisterRep) Reset() {
	*x = RegisterRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRep) ProtoMessage() {}

func (x *RegisterRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRep.ProtoReflect.Descriptor instead.
func (*RegisterRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//注册客户端
type RegisterClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  int32    `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Address string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"` //服务器地址
	Events  []string `protobuf:"bytes,4,rep,name=Events,proto3" json:"Events,omitempty"`   //注册监听事件
}

func (x *RegisterClientReq) Reset() {
	*x = RegisterClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientReq) ProtoMessage() {}

func (x *RegisterClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientReq.ProtoReflect.Descriptor instead.
func (*RegisterClientReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterClientReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RegisterClientReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterClientReq) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type DisRegisterClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  int32  `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *DisRegisterClientReq) Reset() {
	*x = DisRegisterClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisRegisterClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisRegisterClientReq) ProtoMessage() {}

func (x *DisRegisterClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisRegisterClientReq.ProtoReflect.Descriptor instead.
func (*DisRegisterClientReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{6}
}

func (x *DisRegisterClientReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *DisRegisterClientReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

//注册路由
type RegisterMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  int32       `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Address string      `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Data    []*MenuInfo `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RegisterMenuReq) Reset() {
	*x = RegisterMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMenuReq) ProtoMessage() {}

func (x *RegisterMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMenuReq.ProtoReflect.Descriptor instead.
func (*RegisterMenuReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterMenuReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RegisterMenuReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterMenuReq) GetData() []*MenuInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//注册区服
type RegisterZoneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   int32  `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	ZoneId   int32  `protobuf:"varint,2,opt,name=ZoneId,proto3" json:"ZoneId,omitempty"`
	ZoneName string `protobuf:"bytes,3,opt,name=ZoneName,proto3" json:"ZoneName,omitempty"`
	IsGrey   bool   `protobuf:"varint,4,opt,name=IsGrey,proto3" json:"IsGrey,omitempty"` //是否是灰度服
}

func (x *RegisterZoneReq) Reset() {
	*x = RegisterZoneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterZoneReq) ProtoMessage() {}

func (x *RegisterZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterZoneReq.ProtoReflect.Descriptor instead.
func (*RegisterZoneReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterZoneReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RegisterZoneReq) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *RegisterZoneReq) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *RegisterZoneReq) GetIsGrey() bool {
	if x != nil {
		return x.IsGrey
	}
	return false
}

//注册道具
type RegisterItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32       `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Data   []*ItemInfo `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RegisterItemReq) Reset() {
	*x = RegisterItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterItemReq) ProtoMessage() {}

func (x *RegisterItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterItemReq.ProtoReflect.Descriptor instead.
func (*RegisterItemReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterItemReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RegisterItemReq) GetData() []*ItemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterMallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32       `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Data   []*MallInfo `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RegisterMallReq) Reset() {
	*x = RegisterMallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMallReq) ProtoMessage() {}

func (x *RegisterMallReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMallReq.ProtoReflect.Descriptor instead.
func (*RegisterMallReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterMallReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RegisterMallReq) GetData() []*MallInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *GetRep) Reset() {
	*x = GetRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRep) ProtoMessage() {}

func (x *GetRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRep.ProtoReflect.Descriptor instead.
func (*GetRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{11}
}

func (x *GetRep) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetChannelRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string         `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data []*ChannelInfo `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetChannelRep) Reset() {
	*x = GetChannelRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChannelRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRep) ProtoMessage() {}

func (x *GetChannelRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRep.ProtoReflect.Descriptor instead.
func (*GetChannelRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{12}
}

func (x *GetChannelRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChannelRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChannelRep) GetData() []*ChannelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//渠道属性返回
type GetAttrRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data []*AttrInfo `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetAttrRep) Reset() {
	*x = GetAttrRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttrRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRep) ProtoMessage() {}

func (x *GetAttrRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRep.ProtoReflect.Descriptor instead.
func (*GetAttrRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{13}
}

func (x *GetAttrRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAttrRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAttrRep) GetData() []*AttrInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTypeRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data []*TypeInfo `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetTypeRep) Reset() {
	*x = GetTypeRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTypeRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRep) ProtoMessage() {}

func (x *GetTypeRep) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRep.ProtoReflect.Descriptor instead.
func (*GetTypeRep) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{14}
}

func (x *GetTypeRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTypeRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetTypeRep) GetData() []*TypeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gate_proto protoreflect.FileDescriptor

var file_gate_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x07, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x5d, 0x0a, 0x11, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x48, 0x0a, 0x14, 0x44, 0x69,
	0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x62, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x75, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x5a,
	0x6f, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x5a,
	0x6f, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x47, 0x72, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x47, 0x72, 0x65, 0x79, 0x22,
	0x48, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x0f, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x51,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x32, 0xf5, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x44, 0x69, 0x73, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x0c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12,
	0x30, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x12,
	0x10, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x71, 0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x22,
	0x00, 0x12, 0x1c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x08, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x08, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12,
	0x2b, 0x0a, 0x09, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x0d, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gate_proto_rawDescOnce sync.Once
	file_gate_proto_rawDescData = file_gate_proto_rawDesc
)

func file_gate_proto_rawDescGZIP() []byte {
	file_gate_proto_rawDescOnce.Do(func() {
		file_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_gate_proto_rawDescData)
	})
	return file_gate_proto_rawDescData
}

var file_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gate_proto_goTypes = []interface{}{
	(*ClearAuthReq)(nil),         // 0: ClearAuthReq
	(*ClearAuthRep)(nil),         // 1: ClearAuthRep
	(*PingReq)(nil),              // 2: PingReq
	(*PingRep)(nil),              // 3: PingRep
	(*RegisterRep)(nil),          // 4: RegisterRep
	(*RegisterClientReq)(nil),    // 5: RegisterClientReq
	(*DisRegisterClientReq)(nil), // 6: DisRegisterClientReq
	(*RegisterMenuReq)(nil),      // 7: RegisterMenuReq
	(*RegisterZoneReq)(nil),      // 8: RegisterZoneReq
	(*RegisterItemReq)(nil),      // 9: RegisterItemReq
	(*RegisterMallReq)(nil),      // 10: RegisterMallReq
	(*GetRep)(nil),               // 11: GetRep
	(*GetChannelRep)(nil),        // 12: GetChannelRep
	(*GetAttrRep)(nil),           // 13: GetAttrRep
	(*GetTypeRep)(nil),           // 14: GetTypeRep
	(*MenuInfo)(nil),             // 15: MenuInfo
	(*ItemInfo)(nil),             // 16: ItemInfo
	(*MallInfo)(nil),             // 17: MallInfo
	(*ChannelInfo)(nil),          // 18: ChannelInfo
	(*AttrInfo)(nil),             // 19: AttrInfo
	(*TypeInfo)(nil),             // 20: TypeInfo
}
var file_gate_proto_depIdxs = []int32{
	15, // 0: RegisterMenuReq.Data:type_name -> MenuInfo
	16, // 1: RegisterItemReq.Data:type_name -> ItemInfo
	17, // 2: RegisterMallReq.Data:type_name -> MallInfo
	18, // 3: GetChannelRep.Data:type_name -> ChannelInfo
	19, // 4: GetAttrRep.Data:type_name -> AttrInfo
	20, // 5: GetTypeRep.Data:type_name -> TypeInfo
	5,  // 6: Gate.RegisterClient:input_type -> RegisterClientReq
	6,  // 7: Gate.DisRegisterClient:input_type -> DisRegisterClientReq
	7,  // 8: Gate.RegisterMenu:input_type -> RegisterMenuReq
	2,  // 9: Gate.Ping:input_type -> PingReq
	0,  // 10: Gate.ClearAuth:input_type -> ClearAuthReq
	4,  // 11: Gate.RegisterClient:output_type -> RegisterRep
	4,  // 12: Gate.DisRegisterClient:output_type -> RegisterRep
	4,  // 13: Gate.RegisterMenu:output_type -> RegisterRep
	3,  // 14: Gate.Ping:output_type -> PingRep
	1,  // 15: Gate.ClearAuth:output_type -> ClearAuthRep
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gate_proto_init() }
func file_gate_proto_init() {
	if File_gate_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearAuthRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisRegisterClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterZoneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChannelRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttrRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTypeRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gate_proto_goTypes,
		DependencyIndexes: file_gate_proto_depIdxs,
		MessageInfos:      file_gate_proto_msgTypes,
	}.Build()
	File_gate_proto = out.File
	file_gate_proto_rawDesc = nil
	file_gate_proto_goTypes = nil
	file_gate_proto_depIdxs = nil
}
