// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GateClient is the client API for Gate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateClient interface {
	RegisterClient(ctx context.Context, in *RegisterClientReq, opts ...grpc.CallOption) (*RegisterRep, error)
	DisRegisterClient(ctx context.Context, in *DisRegisterClientReq, opts ...grpc.CallOption) (*RegisterRep, error)
	RegisterMenu(ctx context.Context, in *RegisterMenuReq, opts ...grpc.CallOption) (*RegisterRep, error)
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRep, error)
	ClearAuth(ctx context.Context, in *ClearAuthReq, opts ...grpc.CallOption) (*ClearAuthRep, error)
}

type gateClient struct {
	cc grpc.ClientConnInterface
}

func NewGateClient(cc grpc.ClientConnInterface) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) RegisterClient(ctx context.Context, in *RegisterClientReq, opts ...grpc.CallOption) (*RegisterRep, error) {
	out := new(RegisterRep)
	err := c.cc.Invoke(ctx, "/Gate/RegisterClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) DisRegisterClient(ctx context.Context, in *DisRegisterClientReq, opts ...grpc.CallOption) (*RegisterRep, error) {
	out := new(RegisterRep)
	err := c.cc.Invoke(ctx, "/Gate/DisRegisterClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) RegisterMenu(ctx context.Context, in *RegisterMenuReq, opts ...grpc.CallOption) (*RegisterRep, error) {
	out := new(RegisterRep)
	err := c.cc.Invoke(ctx, "/Gate/RegisterMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRep, error) {
	out := new(PingRep)
	err := c.cc.Invoke(ctx, "/Gate/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) ClearAuth(ctx context.Context, in *ClearAuthReq, opts ...grpc.CallOption) (*ClearAuthRep, error) {
	out := new(ClearAuthRep)
	err := c.cc.Invoke(ctx, "/Gate/ClearAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateServer is the server API for Gate service.
// All implementations must embed UnimplementedGateServer
// for forward compatibility
type GateServer interface {
	RegisterClient(context.Context, *RegisterClientReq) (*RegisterRep, error)
	DisRegisterClient(context.Context, *DisRegisterClientReq) (*RegisterRep, error)
	RegisterMenu(context.Context, *RegisterMenuReq) (*RegisterRep, error)
	Ping(context.Context, *PingReq) (*PingRep, error)
	ClearAuth(context.Context, *ClearAuthReq) (*ClearAuthRep, error)
	mustEmbedUnimplementedGateServer()
}

// UnimplementedGateServer must be embedded to have forward compatible implementations.
type UnimplementedGateServer struct {
}

func (UnimplementedGateServer) RegisterClient(context.Context, *RegisterClientReq) (*RegisterRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedGateServer) DisRegisterClient(context.Context, *DisRegisterClientReq) (*RegisterRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisRegisterClient not implemented")
}
func (UnimplementedGateServer) RegisterMenu(context.Context, *RegisterMenuReq) (*RegisterRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMenu not implemented")
}
func (UnimplementedGateServer) Ping(context.Context, *PingReq) (*PingRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGateServer) ClearAuth(context.Context, *ClearAuthReq) (*ClearAuthRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAuth not implemented")
}
func (UnimplementedGateServer) mustEmbedUnimplementedGateServer() {}

// UnsafeGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateServer will
// result in compilation errors.
type UnsafeGateServer interface {
	mustEmbedUnimplementedGateServer()
}

func RegisterGateServer(s grpc.ServiceRegistrar, srv GateServer) {
	s.RegisterService(&Gate_ServiceDesc, srv)
}

func _Gate_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gate/RegisterClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).RegisterClient(ctx, req.(*RegisterClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_DisRegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisRegisterClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).DisRegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gate/DisRegisterClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).DisRegisterClient(ctx, req.(*DisRegisterClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_RegisterMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).RegisterMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gate/RegisterMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).RegisterMenu(ctx, req.(*RegisterMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gate/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_ClearAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).ClearAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gate/ClearAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).ClearAuth(ctx, req.(*ClearAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gate_ServiceDesc is the grpc.ServiceDesc for Gate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _Gate_RegisterClient_Handler,
		},
		{
			MethodName: "DisRegisterClient",
			Handler:    _Gate_DisRegisterClient_Handler,
		},
		{
			MethodName: "RegisterMenu",
			Handler:    _Gate_RegisterMenu_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Gate_Ping_Handler,
		},
		{
			MethodName: "ClearAuth",
			Handler:    _Gate_ClearAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gate.proto",
}
